---
title: "SURE Project"
author: ""
date: "`r format(Sys.Date(), '%B %d, %Y')`"
graphics: yes
output: pdf_document
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      cache = T,
                      eval = T,
                      message = F,
                      warning = F,
                      fig.width = 8,
                      fig.height = 10,
                      fig.align = 'center')
library(sp)
library(sf)
library(terra)
library(raster)
library(rgdal)
library(pander)
library(magrittr)
library(ggplot2)
library(dplyr)
library(tidyr)
library(RColorBrewer)
library(here)
library(plotrix)
```

## Objective

Validate predictions using LANDSAT data for kelp area.

```{r}
# clear environment
rm(list = ls())

# set a directory
r.dir <- '/Volumes/GoogleDrive/My Drive/SURE_Project/Spatial_data/Landsat_rasters'
d.dir <- here('data')
# output
o.dir <- '/Volumes/Chunting HD/Git_Repositories/Chunting_Spatial_Analyses/spatial_data/Landsat_rasters'
```

## Aggregate LANDSAT data

```{r}
year <- 1984:2021

# # list files
# n.files <- dir(r.dir)
# n.files <- list.files(r.dir, pattern = '.tif$')
# 
# # choose cell size for aggregate factor
# agg.fact <- 120/30 # ~120m
# # agg.fact <- 150/30 # ~150m
# # agg.fact <- 300/30 # ~300m
# # agg.fact <- 600/30 # ~600m
# # agg.fact <- 900/30 # ~900m
# # agg.fact <- 1500/30 # ~1500m
# 
# for (i in 1:length(n.files)) {
#   area.rast <- rast(paste(r.dir, n.files[i], sep = '/'))
#   # aggregate
#   agg.rast <- aggregate(area.rast, fact = agg.fact, fun = mean, na.rm = TRUE)
#   # write to file
#   writeRaster(agg.rast,
#               file.path(o.dir, paste0('NC_mean_kelp_area_', year[i], '_120m.tif')),
#               overwrite = TRUE)
# }
```


## Extract Landsat data 

Extract the Landsat data of every year (1984 - 2021) for each site in the North Coast.

```{r}
# # load info on RCCA
# site <- read.csv(paste(d.dir, 'RCCA_North_Coast_sites.csv', sep = '/'))
# 
# # convert from .csv to .shp
# site.shp <- st_as_sf(site, coords = c('longitude', 'latitude'), crs = 'EPSG:4326')
# 
# # initialize an empty data frame
# landsat <- data.frame(site_name = character(), 
#                       year = numeric(),
#                       area = numeric(),
#                       stringsAsFactors = FALSE)
# 
# k.dir <- paste(o.dir, '150m_res', sep = '/')
# k.files <- dir(k.dir)
# k.files <- list.files(k.dir, pattern = '.tif$')
# 
# # extract Landsat data
# for (i in 1:length(k.files)) {
#   kelp.rast <- rast(paste(k.dir, k.files[i], sep = '/'))
#   ext <- terra::extract(kelp.rast, vect(site.shp$geometry)) %>%
#     mutate(site_name = site$site_name, year = as.factor(year[i]), .after = ID) %>%
#     dplyr::select(-ID)
#   landsat <- rbind(landsat, setNames(ext, names(landsat)))
# }
# 
# # save as .csv
# write.csv(landsat, file.path(o.dir, 'NC_mean_kelp_area_1984-2021_150m.csv'))
```

## Plot

```{r}
# kelp density predictions at different resolution
res <- c(120, 300, 900, 1500)

# initialize an empty data frame
kelp.density <- data.frame(site_name = character(),
                           year = factor(),
                           fit = numeric(),
                           longitude = numeric(),
                           latitude = numeric(),
                           resolution = factor())

for (i in res) {
  data <- read.csv(paste(d.dir, paste0('NC_kelp_density_predictions_', i, 'm.csv'), sep ='/')) %>%
    mutate_at(vars(year, site_name), list(as.factor)) %>%
    mutate(resolution = factor(i))
  kelp.density <- rbind(kelp.density, data)
}

# Landsat kelp area at different resolution

# initialize an empty data frame
kelp.area <- data.frame(site_name = character(),
                           year = factor(),
                           area = numeric(),
                           resolution = factor())

for (i in res) {
  data <- read.csv(paste(o.dir, paste0('NC_mean_kelp_area_1984-2021_', i, 'm.csv'), sep ='/')) %>%
    dplyr::select(-X) %>%
    mutate_at(vars(year), list(as.factor)) %>%
    mutate(resolution = factor(i))
  kelp.area <- rbind(kelp.area, data)
}

sites <- kelp.area$site_name %>% unique()
sites <- sites[-c(5, 7, 12, 20, 24, 18)] # remove the ones with no predicted values or Landsat data

for (i in sites) {
  max.kelp.area <- filter(kelp.area, site_name == i)$area %>% max(na.rm = TRUE)
  max.kelp.density <- filter(kelp.density, site_name == i)$fit %>% max(na.rm = TRUE)
  factor <- max.kelp.area / max.kelp.density
  plot <- ggplot() + 
    geom_bar(data = filter(kelp.density, site_name == i),
             aes(x = year, y = fit * factor,
                 fill = ifelse(!is.na(fit) & fit >= 6.6, 'YES', 'NO')),
             stat = 'identity', position = 'dodge', alpha = 0.2) +
    labs(fill = 'fit >= 6.6', title = i) + 
    geom_point(data = filter(kelp.area, site_name == i),
               aes(x = year, y = area), size = 0.5, color = 'black') + 
    geom_line(data = filter(kelp.area, site_name == i),
              aes(x = year, y = area), color = 'black', size = 0.3, group = 1, na.rm = TRUE) + 
    scale_y_continuous(name = 'area',
                       sec.axis = sec_axis(~. / factor, name = 'fit')) +
    facet_wrap(. ~ resolution, nrow = 2) + 
    theme_bw() + 
    theme(axis.text.x = element_text(angle = 90, size = 7),
          plot.title = element_text(hjust = 0.5),
          panel.grid.major = element_blank(),
          legend.title = element_text(size = 9),
          legend.text = element_text(size = 7))
  print(plot)
}
```







