---
title: "SURE Project"
author: ""
date: "`r format(Sys.Date(), '%B %d, %Y')`"
graphics: yes
output: pdf_document
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      cache = T,
                      eval = T,
                      message = F,
                      warning = F,
                      fig.width = 5,
                      fig.height = 3,
                      fig.align = 'center')
library(sp)
library(sf)
library(terra)
library(raster)
library(rgdal)
library(pander)
library(magrittr)
library(ggplot2)
library(dplyr)
library(tidyr)
library(RColorBrewer)
library(here)
library(plotrix)
```

## Objective 

Validate predictions using LANDSAT data for kelp area.

```{r}
# set a directory
w.dir <- here()
d.dir <- here('data')

# load kelp area csv
area_df <- read.csv(paste(d.dir, 'NC_Landsat_kelp_area_1984_2021.csv', sep ='/')) %>%
  glimpse()

# vector of year
area_df$year %>% unique() # 1984 - 2021
area_df$year %>% unique() %>% length() # 38

# Landsat kelp quarters: Q1 = Winter, Q2 = Spring, Q3 = Summer, Q4 = Fall
# make an sf object from dataframe
kelp_area <- area_df %>%
  filter(quarter == 3) %>%
  mutate_at(vars(year, quarter), list(as.factor)) %>%
  st_as_sf(coords = c('lon', 'lat'))

# load kelp density predictions csv
density_df <- read.csv(paste(d.dir, 'NC_kelp_density_predictions.csv', sep ='/')) %>%
  glimpse()

# make an sf object from dataframe
kelp_density <- density_df %>%
  mutate_at(vars(year), list(as.factor)) %>%
  rename(lon = longitude, lat = latitude) %>%
  st_as_sf(coords = c('lon', 'lat'))
```

To compute a distance matrix between each site location and the kelp area for each summer, and find the closest landsat pixel to each site. 

```{r}
# calculate the distance and match predicted kelp density to Landsat kelp area
site_name <- kelp_density[, c('site_name', 'geometry')] %>% unique()
area_1984 <- filter(kelp_area, year == 1984) # 37818
# distance matrix for 1984
mx <- st_distance(st_sfc(area_1984$geometry), st_sfc(site_name$geometry))
colnames(mx) <- site_name$site_name
head(mx)
area_1984 <- area_df %>%
  filter(quarter == 3 & year == 1984) %>%
  select(-year_quarter) %>%
  mutate(
    site_name = apply(mx, 1, FUN = function(x) names(x) [which.min(x)]), 
    .before = lat
  ) 
  # group_by(site_name) %>%
  # summarise(mean_area = mean(area, na.rm = TRUE),
  #           se_area = std.error(area, na.rm = TRUE)) 
head(area_1984)
```

```{r}
# using for loop
# declaring an empty data frame
# kelp_area2 <- data.frame(site_name = character(), 
#                          lat = numeric(),
#                          lon = numeric(), 
#                          area = numeric(),
#                          year = numeric(),
#                          quarter = numeric())
# 
# for (i in c(1984:2021)) {
#   area_year <- filter(kelp_area, year == i)
#   
#   # distance matrix for year i
#   mx <- st_distance(st_sfc(area_year$geometry), st_sfc(site_name$geometry))
#   colnames(mx) <- site_name$site_name
#   
#   area_year <- area_df %>%
#     filter(quarter == 3 & year == i) %>%
#     select(-year_quarter) %>%
#     mutate(
#       site_name = apply(mx, 1, FUN = function(x) names(x) [which.min(x)]), 
#       .before = lat
#     ) 
#   
#   kelp_area2 <- rbind(kelp_area2, area_year)
# }
# dim(kelp_area2) # 38 * 37818 = 1437084
# 
# head(kelp_area2)
# 
# write to file
# write.csv(kelp_area2, file.path(d.dir, 'NC_kelp_area_1984_2021_site_name.csv'), row.names = FALSE)
```

```{r, fig.width = 7, fig.height = 5}
# plotting
kelp_area <- read.csv(paste(d.dir, 'NC_kelp_area_1984_2021_site_name.csv', sep ='/')) %>%
  mutate_at(vars(year), list(as.factor))

kelp_area3 <- kelp_area %>%
  group_by(site_name, year) %>%
  summarise(mean_area = mean(area, na.rm = TRUE),
            se_area = std.error(area, na.rm = TRUE))
  
sites <- kelp_area3$site_name %>% unique()

for (i in sites) {
  plot <- ggplot() +
    geom_bar(data = filter(kelp_density, site_name == i),
             aes(x = year, y = fit,
                 fill = ifelse(!is.na(fit) & fit >= 6.6, 'YES', 'NO')),
             stat = 'identity', position = 'dodge', alpha = 0.2) + 
    geom_pointrange(data = filter(kelp_area3, site_name == i),
                    aes(x = year, y = mean_area, 
                        ymin = mean_area - se_area, 
                        ymax = mean_area + se_area),
                    alpha = 0.5, size = 0.3) +
    geom_line(data = filter(kelp_area3, site_name == i),
              aes(x = year, y = mean_area, group = 1), size = 0.3) + 
    scale_y_continuous(name = 'area',
                       sec.axis = sec_axis(~./2, name = 'fit')) + 
    labs(fill = 'fit >= 6.6', title = i) + 
    theme_bw() + 
    theme(axis.text.x = element_text(angle = 90, size = 7),
          plot.title = element_text(hjust = 0.5),
          panel.grid.major = element_blank(),
          legend.title = element_text(size = 9),
          legend.text = element_text(size = 7))
  print(plot)
}  
```
