---
title: "SURE Project"
author: ""
date: "`r format(Sys.Date(), '%B %d, %Y')`"
graphics: yes
output: pdf_document
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      cache = T,
                      eval = T,
                      message = F,
                      warning = F,
                      fig.align = 'center')
library(Amelia) # to map missing data
library(here)
library(tidyverse)
library(dplyr)
library(ggplot2) 
library(caret) ## For model fitting and evaluation
library(RANN)
library(corrplot)
library(rsample)
library(yardstick) ## to evaluate a model
library(visreg)  ## For visualizing regression models
library(plotROC) ## For constructing ROC curves
library(mgcv)    ## For fitting GAM models
library(kernlab) ## Contains an example dataset
library(glmnet)  ## For fitting regularized models
library(pROC)
library(ROCR)
library(car)
library(OddsPlotty) # to plot from the caret package
library(tidymodels) # modern version of caret
library(cutpointr) # Find optimal cutoff point for binary classification
library(bestglm) # Best subset GLM : The function bestglm selects the best 
                 # subset of inputs for the glm family
library(MASS) # Stepwise regression
library(reshape2)
library(sp)
library(sf)
library(rgdal)
library(raster) 
library(terra)
library(RColorBrewer)
# library(geobr)
library(ggspatial)
library(ggrepel)
library(forcats)
library(beepr)
library(gridExtra)
library(FSSgam)
library(viridis)
library(hrbrthemes)
library(gplots)
library(beepr)
library(stringr)
library(purrr)
library(modelr)
library(broom)
library(tidyr)
library(latex2exp)
library(lemon)
```

```{r}
rm(list = ls())

# set a directory
w.dir <- here()
d.dir <- here('data')
```

```{r}
overall.summary <- read.csv(paste(d.dir, 'North_Coast_cv_summary_stats.csv', sep = '/')) %>%
  mutate_at(vars(resolution), list(as.factor))
head(overall.summary)
```

```{r}
p <- ggplot(overall.summary %>% 
              dplyr::filter(summary_stat != 'mean_R.Sqr_test' & summary_stat != 'mean_residuals'),
            aes(x = resolution, y = mean_stat, color = resolution)) + 
  geom_point(size = 5) + 
  facet_wrap(~ summary_stat, scales = 'free') + 
  scale_color_viridis(discrete = T) + 
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 45, h = 1))

p
```

```{r, fig.width=7, fig.height=10}
new.label <- c('mean_R.Sqr_test' = 'R-squared',
               'dev.exp' = 'Deviance Explained', 
               'rmse' = 'RMSE')

overall.summary$summary_stat <- factor(overall.summary$summary_stat, 
                                       levels = c('dev.exp', 'mean_R.Sqr_test', 'rmse'))

overall.summary %>% 
  dplyr::filter(summary_stat %in% c('dev.exp', 'mean_R.Sqr_test', 'rmse')) %>%
  dplyr::select(-resolution) %>% 
  mutate(resolution = factor(rep(c('120x120', '300x300', '900x900', '1500x1500'), each = 3),
                             levels = c('120x120', '300x300', '900x900', '1500x1500'))) %>%
  ggplot(aes(x = resolution, y = mean_stat, color = resolution)) +
  geom_point(size = 4) + 
  geom_errorbar(aes(ymin = mean_stat - se_stat, ymax = mean_stat + se_stat),
                width = 0.15, position = position_dodge(0.9), alpha = 4, size = 1) +
  facet_wrap(~ summary_stat, 
             nrow = 3, scales = 'free_y',
             labeller = labeller(summary_stat = new.label)) + 
  guides(color = FALSE) + 
  theme_bw() + 
  labs(y = '', x = 'Resolution') + 
  theme(axis.text.x = element_text(angle = 30, v = 0.5, face = 'bold'),
        legend.position = 'bottom',
        legend.key.size = unit(1, 'line'), 
        axis.title.x = element_text(face = 'bold'),
        axis.title.y = element_text(face = 'bold'),
        legend.text = element_text(face = 'bold'),
        panel.grid.major = element_blank(),
        strip.text = element_text(face = 'bold'),
        strip.background = element_rect(colour = 'black', fill = 'white'),
        text = element_text(size = 30))
```

```{r}
overall.summary %>% 
  dplyr::filter(summary_stat == 'dev.exp' & summary_stat == 'rmse')
```

```{r, fig.width=7, fig.height=5}
r.sq <- overall.summary %>% 
  dplyr::filter(summary_stat == 'mean_R.Sqr_test') %>%
  dplyr::select(-resolution) %>%
  mutate(resolution = factor(c('120x120', '300x300', '900x900', '1500x1500'),
                             levels = c('120x120', '300x300', '900x900', '1500x1500'))) %>%
  ggplot(aes(x = resolution, y = mean_stat, fill = resolution)) + 
  geom_bar(position = 'dodge', stat = 'identity', color = 'black') + 
  geom_errorbar(aes(ymin = mean_stat - se_stat, ymax = mean_stat + se_stat),
                width = 0.15, position = position_dodge(0.9), alpha = 2) +
  labs(x = 'Resolution', y = TeX('$\\R^2_{test}$'), fill = "") + 
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 45, h = 1),
        legend.position = 'bottom',
        legend.key.size = unit(1, 'line'), 
        axis.title.x = element_text(face = 'bold'),
        axis.title.y = element_text(face = 'bold'),
        legend.text = element_text(face = 'bold'),
        panel.grid.major = element_blank(),
        text = element_text(size = 30))

r.sq
```

```{r, fig.width=7, fig.height=5}
rmse <- overall.summary %>% 
  dplyr::filter(summary_stat == 'rmse') %>%
  dplyr::select(-resolution) %>%
  mutate(resolution = factor(c('120x120', '300x300', '900x900', '1500x1500'),
                             levels = c('120x120', '300x300', '900x900', '1500x1500'))) %>%
  ggplot(aes(x = resolution, y = mean_stat, fill = resolution)) + 
  geom_bar(position = 'dodge', stat = 'identity', color = 'black') + 
  geom_errorbar(aes(ymin = mean_stat - se_stat, ymax = mean_stat + se_stat),
                width = 0.15, position = position_dodge(0.9), alpha = 2) +
  labs(x = 'Resolution', y = TeX('RMSE'), fill = "") + 
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 45, h = 1),
        legend.position = 'bottom',
        legend.key.size = unit(1, 'line'), 
        axis.title.x = element_text(face = 'bold'),
        axis.title.y = element_text(face = 'bold'),
        legend.text = element_text(face = 'bold'),
        panel.grid.major = element_blank(),
        text = element_text(size = 30))

rmse
```

```{r}
data.frame(predictor = c('Urchin Density', 'Max Nitrate', 'Wave Height', 'Orbital Velocity'),
           resolution = c('300x300 m', '5000x5000 m', '1000x100 m' , '30x30 m')) %>%
  pander()
```






