---
title: "SURE Project"
author: ""
date: "`r format(Sys.Date(), '%B %d, %Y')`"
graphics: yes
output: pdf_document
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      cache = T,
                      eval = T,
                      message = F,
                      warning = F,
                      fig.align = 'center')
library(Amelia) # to map missing data
library(here)
library(tidyverse)
library(dplyr)
library(ggplot2) 
library(caret) ## For model fitting and evaluation
library(RANN)
library(corrplot)
library(rsample)
library(yardstick) ## to evaluate a model
library(visreg)  ## For visualizing regression models
library(plotROC) ## For constructing ROC curves
library(mgcv)    ## For fitting GAM models
library(kernlab) ## Contains an example dataset
library(glmnet)  ## For fitting regularized models
library(pROC)
library(ROCR)
library(car)
library(OddsPlotty) # to plot from the caret package
library(tidymodels) # modern version of caret
library(cutpointr) # Find optimal cutoff point for binary classification
library(bestglm) # Best subset GLM : The function bestglm selects the best 
                 # subset of inputs for the glm family
library(MASS) # Stepwise regression
library(reshape2)
library(sp)
library(sf)
library(rgdal)
library(raster) 
library(terra)
library(RColorBrewer)
# library(geobr)
library(ggspatial)
library(ggrepel)
library(forcats)
library(beepr)
library(gridExtra)
library(FSSgam)
library(viridis)
library(hrbrthemes)
library(gplots)
library(beepr)
library(stringr)
```

# Prepare predictor variables

```{r}
# clear environment
rm(list = ls())

# set a directory
w.dir <- here()
d.dir <- here('data')

# env predictors
e.dir <- '/Volumes/GoogleDrive/My Drive/SURE_Project/Spatial_data/Predictors' 
o.dir <- '/Volumes/Chunting HD/Git_Repositories/Chunting_Spatial_Analyses/spatial_data/Predictors'

## purple sea urchins ----
urch.dir <- paste(o.dir, 'urchins', 'log_sp_predictions', sep = '/')
urchin <- paste(e.dir, 'urchins', 'log_sp_predictions', sep = '/')

# load raster data
u.files <- list.files(urchin, pattern = '.tif', full.name = TRUE) 

# list names to load onto the Environment
names.list <- list.files(urchin, pattern = '.tif$')
names.list <- str_replace(names.list, '.tif$', '')

# load csv files as a list
tfiles <- lapply(u.files, rast)

# stack them
urchin.stack <- c()

# use do.call to create a raster otherwise it creates a list
urchin.stack <- do.call('c', tfiles) # 18

# agg/diagg
# urchin.120 <- disagg(urchin.stack, fact = 2.5)
# writeRaster(urchin.120, file.path(urch.dir, 'Log_Purple_Urchins_120m.tif'), overwrite = TRUE)
# urchin.300 <- urchin.stack
# writeRaster(urchin.300, file.path(urch.dir, 'Log_Purple_Urchins_300m.tif'), overwrite = TRUE)
# urchin.900 <- aggregate(urchin.stack, fact = 3, fun = mean, na.rm = TRUE)
# writeRaster(urchin.900, file.path(urch.dir, 'Log_Purple_Urchins_900m.tif'), overwrite = TRUE)
# urchin.1500 <- aggregate(urchin.stack, fact = 5, fun = mean, na.rm = TRUE)
# writeRaster(urchin.1500, file.path(urch.dir, 'Log_Purple_Urchins_1500m.tif'), overwrite = TRUE)

## nitrate ---- 
nit.dir <- paste(o.dir, 'Nitrate', sep = '/')
max_nit <- rast(paste(e.dir, 'Nitrate', 'Max_Monthly_Nitrate.tif', sep = '/')) # 24

# agg/diagg
# nitrate.120 <- disagg(max_nit, fact = 45)
# writeRaster(nitrate.120, file.path(nit.dir, 'Max_Monthly_Nitrate_120m.tif'), overwrite = TRUE)
# nitrate.300 <- disagg(max_nit, fact = 18)
# writeRaster(nitrate.300, file.path(nit.dir, 'Max_Monthly_Nitrate_300m.tif'), overwrite = TRUE)
# nitrate.900 <- disagg(max_nit, fact = 6)
# writeRaster(nitrate.900, file.path(nit.dir, 'Max_Monthly_Nitrate_900m.tif'), overwrite = TRUE)
# nitrate.1500 <- disagg(max_nit, fact = 4)
# writeRaster(nitrate.1500, file.path(nit.dir, 'Max_Monthly_Nitrate_1500m.tif'), overwrite = TRUE)

## wave height ----
wave.dir <- paste(o.dir, 'waves', 'wh_max', sep = '/')
whmax <- paste(e.dir, 'waves', 'wh_max', sep = '/')

# list files in source
n.files <- list.files(whmax, pattern = '.tif$', full.name = TRUE)

# list names to load onto the Environment
names.list <- list.files(whmax, pattern = '.tif$')
names.list <- str_replace(names.list, '.tif$', '')

# load csv files as a list
tfiles <- lapply(n.files, rast) # this is a list

# stack them
whmax.stack <- c()

# use do.call to create a raster otherwise it creates a list
whmax.stack <- do.call('c', tfiles) # 18

# agg/diagg
# whmax.120 <- disagg(whmax.stack, fact = 9)
# writeRaster(whmax.120, file.path(wave.dir, 'wh_max_120m.tif'), overwrite = TRUE)
# whmax.300 <- disagg(whmax.stack, fact = 4)
# writeRaster(whmax.300, file.path(wave.dir, 'wh_max_300m.tif'), overwrite = TRUE)
# whmax.900 <- whmax.stack
# writeRaster(whmax.900, file.path(wave.dir, 'wh_max_900m.tif'), overwrite = TRUE)
# whmax.1500 <- aggregate(whmax.stack, fact = 2, fun = mean, na.rm = TRUE)
# writeRaster(whmax.1500, file.path(wave.dir, 'wh_max_1500m.tif'), overwrite = TRUE)

## orbital velocity ----
ubr.dir <- paste(o.dir, 'orbital_vel', sep = '/')
ubr <- rast(paste(e.dir, 'orbital_vel', 'UBR_Max_30m_NC.tif', sep = '/')) # 18

# agg/disagg
# ubr.120 <- aggregate(ubr, fact = 4, fun = mean, na.rm = TRUE)
# writeRaster(ubr.120, file.path(ubr.dir, 'UBR_Max_120m.tif'), overwrite = TRUE)
# ubr.300 <- aggregate(ubr, fact = 10, fun = mean, na.rm = TRUE)
# writeRaster(ubr.300, file.path(ubr.dir, 'UBR_Max_300m.tif'), overwrite = TRUE)
# ubr.900 <- aggregate(ubr, fact = 30, fun = mean, na.rm = TRUE)
# writeRaster(ubr.900, file.path(ubr.dir, 'UBR_Max_900m.tif'), overwrite = TRUE)
# ubr.1500 <- aggregate(ubr, fact = 50, fun = mean, na.rm = TRUE)
# writeRaster(ubr.1500, file.path(ubr.dir, 'UBR_Max_1500m.tif'), overwrite = TRUE)
```

```{r}
# read the .csv file
site <- read.csv(paste(d.dir, 'RCCA_North_Coast_sites.csv', sep = '/')) 
# convert from .csv to .shp
site.shp <- st_as_sf(site, coords = c('longitude', 'latitude'), crs = 'EPSG:4326')
```

```{r}
years <- read.csv(paste0(d.dir, '/RCCA_North_Coast_sites.csv'))

# get the sites from with pre MHW data 
# 3 or more pre MHW surveys
ncsites <- years %>%
  mutate_at(vars(site_name), list(as.factor)) %>%
  # get only sites with pre MHW data
  filter(pre.mhw.years > 2) %>%
  droplevels()

df <- read.csv(paste0(d.dir, '/RCCA_kelp_inverts_NC_depth-zones_wave_clim_temp_nit_subs_orbvel_npp.csv')) %>%
  mutate_at(vars(site_name, month, year, transect, zone), list(as.factor)) %>%
  mutate(zone_new = case_when(
    transect == '1' ~ 'OUTER',
    transect == '2' ~ 'OUTER',
    transect == '3' ~ 'OUTER',
    transect == '4' ~ 'INNER',
    transect == '5' ~ 'INNER',
    transect == '6' ~ 'INNER'
  )) %>%
  dplyr::select(-zone) %>%
  rename(zone = zone_new) %>%
  mutate_at(vars(zone), list(as.factor)) %>%
  relocate(zone, .after = transect)

# get the sites for North Coast model 
df.nc <- df %>%
  dplyr::select(-c(latitude, longitude)) %>%
  right_join(ncsites, by = c('site_name')) %>%
  droplevels() %>%
  relocate(c(latitude, longitude), .after = zone)

# choose variables and transform needed
dat1 <- df.nc %>%
  dplyr::select(
    # Factors 
    latitude, longitude, site_name, year, transect, zone,
    # Bio vars
    den_NERLUE , den_MESFRAAD , den_STRPURAD , den_PYCHEL, den_HALRUF,
    # Nitrate vars 
    Days_10N, 
    Min_Monthly_Nitrate, 
    Max_Monthly_Nitrate,
    Mean_Monthly_Nitrate,
    Mean_Monthly_Upwelling_Nitrate,
    Max_Monthly_Anomaly_Nitrate,
    Mean_Monthly_Summer_Nitrate,
    # Temperature vars
    Days_16C ,
    Mean_Monthly_Temp ,
    Mean_Monthly_Summer_Temp,
    MHW_Upwelling_Days, 
    Min_Monthly_Anomaly_Temp,
    Max_Monthly_Anomaly_Upwelling_Temp,
    Min_Monthly_Temp, 
    Mean_Monthly_Upwelling_Temp,
    #wh.95 ,   wh.max,
    npgo_mean , mei_mean,
    # substrate
    mean_depth, mean_prob_of_rock, mean_vrm, mean_slope,
    # waves
    wh_max, wh_mean, mean_waveyear, wh_95prc,
    # Orb vel
    UBR_Mean, UBR_Max,
    # NPP
    Mean_Monthly_NPP, Max_Monthly_NPP_Upwelling, Mean_Monthly_NPP_Upwelling, Min_Monthly_NPP
  ) %>%
  # Bio transformations
  mutate(
    log_den_NERLUE = log(den_NERLUE + 1),
    log_den_MESFRAAD = log(den_MESFRAAD + 1),
    log_den_STRPURAD = log(den_STRPURAD + 1),
    log_den_PYCHEL = log(den_PYCHEL + 1),
    log_den_HALRUF = log(den_HALRUF + 1),
    log_mean_vrm = log(mean_vrm + 1)
  ) %>%
  dplyr::select(-c(den_NERLUE, den_MESFRAAD, den_STRPURAD, den_PYCHEL, den_HALRUF, mean_vrm)) %>%
  # Temperature transformations
  mutate(log_Days_16C = log(Days_16C + 1)) %>%
  dplyr::select(-c(Days_16C)) %>%
  # Orb vel transformations
  mutate(
    log_UBR_Mean = log(UBR_Mean + 1), 
    log_UBR_Max = log(UBR_Max + 1)
  ) %>%
  dplyr::select(-c(UBR_Mean, UBR_Max)) %>%
  # NPP transformations
  mutate(
    log_Mean_Monthly_NPP_Upwelling = log(Mean_Monthly_NPP_Upwelling + 1),
    log_Min_Monthly_NPP = log(Min_Monthly_NPP + 1)
  ) %>%
  dplyr::select(-c(Mean_Monthly_NPP_Upwelling, Min_Monthly_NPP))

dat2 <- dat1 %>%
  dplyr::select(latitude, longitude, site_name, year, zone, log_den_NERLUE) 
```

## 120x120

```{r}
data.120 <- data.frame(site_name = factor(),
                       year = factor(),
                       log_den_STRPURAD = numeric())
  
year <- c(2004:2021)
urchin.120 <- rast(paste(urch.dir, 'Log_Purple_Urchins_120m.tif', sep = '/')) 

for (i in 1:length(year)) {
  urch.rast <- urchin.120[[i]]
  urch.ext <- terra::extract(urch.rast, vect(site.shp$geometry)) %>%
    mutate(site_name = as.factor(site$site_name), year = as.factor(year[i]), .before = fit) %>%
    dplyr::select(-ID) 
  data.120 <- rbind(data.120, setNames(urch.ext, names(data.120)))
}

max_nit.120 <- rast(paste(nit.dir, 'Max_Monthly_Nitrate_120m.tif', sep = '/')) 
max_nit.120 <- max_nit.120[[-c(1:6)]] # remove years before 2004
whmax.120 <- rast(paste(wave.dir, 'wh_max_120m.tif', sep = '/')) 
# ubr.120 <- rast(paste(ubr.dir, 'UBR_Max_120m.tif', sep = '/')) 
# ubr.120 <- terra::project(ubr.120, 'epsg:4326')
# writeRaster(ubr.120, file.path(ubr.dir, 'UBR_Max_120m_projected.tif'), overwrite = TRUE)
ubr.120 <- rast(paste(ubr.dir, 'UBR_Max_120m_projected.tif', sep = '/')) 

nit.df <- data.frame(Max_Monthly_Nitrate = numeric())
whmax.df <- data.frame(wh_max = numeric())
ubr.df <- data.frame(UBR_Max = numeric())
for (i in 1:length(year)) {
  nit.rast <- max_nit.120[[i]]
  nit.ext <- terra::extract(nit.rast, vect(site.shp$geometry)) %>%
    dplyr::select(-ID) 
  nit.df <- rbind(nit.df, setNames(nit.ext, names(nit.df)))
  
  whmax.rast <- whmax.120[[i]]
  whmax.ext <- terra::extract(whmax.rast, vect(site.shp$geometry)) %>%
    dplyr::select(-ID) 
  whmax.df <- rbind(whmax.df, setNames(whmax.ext, names(whmax.df)))
  
  ubr.rast <- ubr.120[[i]]
  ubr.ext <- terra::extract(ubr.rast, vect(site.shp$geometry)) %>%
    dplyr::select(-ID) 
  ubr.df <- rbind(ubr.df, setNames(ubr.ext, names(ubr.df)))
}
```

```{r}
data.120 <- cbind(data.120, nit.df, whmax.df, ubr.df) 
df.120 <- data.120 %>%
  mutate(log_UBR_Max = log(UBR_Max)) %>% # log transformation of UBR
  dplyr::select(-UBR_Max)
```

```{r}
dat.120 <- left_join(dat2, df.120, by = c('site_name', 'year'))
# write.csv(dat.120, file.path(d.dir, '/RCCA_kelp_inverts_NC_depth-zones_wave_clim_temp_nit_subs_orbvel_npp_120m.csv'), row.names = FALSE)

# drop NAs
dat2.120 <- dat.120 %>%
  drop_na() # 434

# divide data into train and test
# split data into a training set (75%), and a testing set (25%)
set.seed(110122)
inTraining <- createDataPartition(dat2.120$log_den_NERLUE, p = 0.75, list = FALSE)
train.120 <- dat2.120[inTraining, ]
test.120 <- dat2.120[-inTraining, ]

# run GAM
gam120 <- gam(formula = log_den_NERLUE ~ 
              s(log_den_STRPURAD, k = 5, bs = "cr") + # purple sea urchins
              s(Max_Monthly_Nitrate, k = 5, bs = "cr") + 
              s(wh_max, k = 5, bs = "cr") + # wave height
              s(log_UBR_Max, k = 4, bs = "cr") + # orbital velocity, continuous variables
              s(site_name, zone, bs = "re") + # zone is nested within site
              s(year, bs = "re"), # discrete variables, categorical
              # random factor
              family = tw(), data = train.120, method = 'REML')

# check GAM
gam120$aic
gam120$deviance
summary(gam120)
gam.check(gam120)
```

```{r}
# plot observed vs predicted

# fit the testing data
fits120 <- predict.gam(gam120, newdata = test.120, type = 'response', se.fit = T)

predicts.all <- test.120 %>%
  data.frame(fits120) %>%
  ungroup()

library(ggpmisc)

my.formula <- y ~ x

p <- predicts.all %>%
  ggplot(aes(x = fit, y = log_den_NERLUE)) + 
  geom_smooth(method = 'lm', se = FALSE, color = 'black', formula = my.formula) + 
  stat_poly_eq(
    formula = my.formula,
    aes(label = paste(..eq.label.., ..rr.label.., sep = '~~~')),
    parse = TRUE
  ) + 
  geom_point() + 
  labs(x = 'Predicted', y = 'Observed', title = 'N. luetkeana') + 
  theme_bw()
p
```

## 300x300

```{r}
data.300 <- data.frame(site_name = factor(),
                       year = factor(),
                       log_den_STRPURAD = numeric())
  
year <- c(2004:2021)
urchin.300 <- rast(paste(urch.dir, 'Log_Purple_Urchins_300m.tif', sep = '/')) 

for (i in 1:length(year)) {
  urch.rast <- urchin.300[[i]]
  urch.ext <- terra::extract(urch.rast, vect(site.shp$geometry)) %>%
    mutate(site_name = as.factor(site$site_name), year = as.factor(year[i]), .before = fit) %>%
    dplyr::select(-ID) 
  data.300 <- rbind(data.300, setNames(urch.ext, names(data.300)))
}

max_nit.300 <- rast(paste(nit.dir, 'Max_Monthly_Nitrate_300m.tif', sep = '/')) 
max_nit.300 <- max_nit.300[[-c(1:6)]] # remove years before 2004
whmax.300 <- rast(paste(wave.dir, 'wh_max_300m.tif', sep = '/')) 
# ubr.300 <- rast(paste(ubr.dir, 'UBR_Max_300m.tif', sep = '/'))
# ubr.300 <- terra::project(ubr.300, 'epsg:4326')
# writeRaster(ubr.300, file.path(ubr.dir, 'UBR_Max_300m_projected.tif'), overwrite = TRUE)
ubr.300 <- rast(paste(ubr.dir, 'UBR_Max_300m_projected.tif', sep = '/')) 

nit.df <- data.frame(Max_Monthly_Nitrate = numeric())
whmax.df <- data.frame(wh_max = numeric())
ubr.df <- data.frame(UBR_Max = numeric())
for (i in 1:length(year)) {
  nit.rast <- max_nit.300[[i]]
  nit.ext <- terra::extract(nit.rast, vect(site.shp$geometry)) %>%
    dplyr::select(-ID) 
  nit.df <- rbind(nit.df, setNames(nit.ext, names(nit.df)))
  
  whmax.rast <- whmax.300[[i]]
  whmax.ext <- terra::extract(whmax.rast, vect(site.shp$geometry)) %>%
    dplyr::select(-ID) 
  whmax.df <- rbind(whmax.df, setNames(whmax.ext, names(whmax.df)))
  
  ubr.rast <- ubr.300[[i]]
  ubr.ext <- terra::extract(ubr.rast, vect(site.shp$geometry)) %>%
    dplyr::select(-ID) 
  ubr.df <- rbind(ubr.df, setNames(ubr.ext, names(ubr.df)))
}
```

```{r}
data.300 <- cbind(data.300, nit.df, whmax.df, ubr.df) 
df.300 <- data.300 %>%
  mutate(log_UBR_Max = log(UBR_Max)) %>% # log transformation of UBR
  dplyr::select(-UBR_Max)
```

```{r}
dat.300 <- left_join(dat2, df.300, by = c('site_name', 'year'))
# write.csv(dat.300, file.path(d.dir, '/RCCA_kelp_inverts_NC_depth-zones_wave_clim_temp_nit_subs_orbvel_npp_300m.csv'), row.names = FALSE)

# drop NAs
dat2.300 <- dat.300 %>%
  drop_na() # 434

# divide data into train and test
# split data into a training set (75%), and a testing set (25%)
set.seed(110122)
inTraining <- createDataPartition(dat2.300$log_den_NERLUE, p = 0.75, list = FALSE)
train.300 <- dat2.300[inTraining, ]
test.300 <- dat2.300[-inTraining, ]

# run GAM
gam300 <- gam(formula = log_den_NERLUE ~ 
              s(log_den_STRPURAD, k = 5, bs = "cr") + # purple sea urchins
              s(Max_Monthly_Nitrate, k = 5, bs = "cr") + 
              s(wh_max, k = 5, bs = "cr") + # wave height
              s(log_UBR_Max, k = 4, bs = "cr") + # orbital velocity, continuous variables
              s(site_name, zone, bs = "re") + # zone is nested within site
              s(year, bs = "re"), # discrete variables, categorical
              # random factor
              family = tw(), data = train.300, method = 'REML')

# check GAM
gam300$aic
gam300$deviance
summary(gam300)
gam.check(gam300)
```

```{r}
# plot observed vs predicted

# fit the testing data
fits300 <- predict.gam(gam300, newdata = test.300, type = 'response', se.fit = T)

predicts.all <- test.300 %>%
  data.frame(fits300) %>%
  ungroup()

library(ggpmisc)

my.formula <- y ~ x

p <- predicts.all %>%
  ggplot(aes(x = fit, y = log_den_NERLUE)) + 
  geom_smooth(method = 'lm', se = FALSE, color = 'black', formula = my.formula) + 
  stat_poly_eq(
    formula = my.formula,
    aes(label = paste(..eq.label.., ..rr.label.., sep = '~~~')),
    parse = TRUE
  ) + 
  geom_point() + 
  labs(x = 'Predicted', y = 'Observed', title = 'N. luetkeana') + 
  theme_bw()
p
```

## 900x900

```{r}
data.900 <- data.frame(site_name = factor(),
                       year = factor(),
                       log_den_STRPURAD = numeric())
  
year <- c(2004:2021)
urchin.900 <- rast(paste(urch.dir, 'Log_Purple_Urchins_900m.tif', sep = '/')) 

for (i in 1:length(year)) {
  urch.rast <- urchin.900[[i]]
  urch.ext <- terra::extract(urch.rast, vect(site.shp$geometry)) %>%
    mutate(site_name = as.factor(site$site_name), year = as.factor(year[i]), .before = fit) %>%
    dplyr::select(-ID) 
  data.900 <- rbind(data.900, setNames(urch.ext, names(data.900)))
}

max_nit.900 <- rast(paste(nit.dir, 'Max_Monthly_Nitrate_900m.tif', sep = '/')) 
max_nit.900 <- max_nit.900[[-c(1:6)]] # remove years before 2004
whmax.900 <- rast(paste(wave.dir, 'wh_max_900m.tif', sep = '/')) 
# ubr.900 <- rast(paste(ubr.dir, 'UBR_Max_900m.tif', sep = '/'))
# ubr.900 <- terra::project(ubr.900, 'epsg:4326')
# writeRaster(ubr.900, file.path(ubr.dir, 'UBR_Max_900m_projected.tif'), overwrite = TRUE)
ubr.900 <- rast(paste(ubr.dir, 'UBR_Max_900m_projected.tif', sep = '/')) 

nit.df <- data.frame(Max_Monthly_Nitrate = numeric())
whmax.df <- data.frame(wh_max = numeric())
ubr.df <- data.frame(UBR_Max = numeric())
for (i in 1:length(year)) {
  nit.rast <- max_nit.900[[i]]
  nit.ext <- terra::extract(nit.rast, vect(site.shp$geometry)) %>%
    dplyr::select(-ID) 
  nit.df <- rbind(nit.df, setNames(nit.ext, names(nit.df)))
  
  whmax.rast <- whmax.900[[i]]
  whmax.ext <- terra::extract(whmax.rast, vect(site.shp$geometry)) %>%
    dplyr::select(-ID) 
  whmax.df <- rbind(whmax.df, setNames(whmax.ext, names(whmax.df)))
  
  ubr.rast <- ubr.900[[i]]
  ubr.ext <- terra::extract(ubr.rast, vect(site.shp$geometry)) %>%
    dplyr::select(-ID) 
  ubr.df <- rbind(ubr.df, setNames(ubr.ext, names(ubr.df)))
}
```

```{r}
data.900 <- cbind(data.900, nit.df, whmax.df, ubr.df) 
df.900 <- data.900 %>%
  mutate(log_UBR_Max = log(UBR_Max)) %>% # log transformation of UBR
  dplyr::select(-UBR_Max)
```

```{r}
dat.900 <- left_join(dat2, df.900, by = c('site_name', 'year'))
# write.csv(dat.900, file.path(d.dir, '/RCCA_kelp_inverts_NC_depth-zones_wave_clim_temp_nit_subs_orbvel_npp_900m.csv'), row.names = FALSE)

# drop NAs
dat2.900 <- dat.900 %>%
  drop_na() # 434

# divide data into train and test
# split data into a training set (75%), and a testing set (25%)
set.seed(110122)
inTraining <- createDataPartition(dat2.900$log_den_NERLUE, p = 0.75, list = FALSE)
train.900 <- dat2.900[inTraining, ]
test.900 <- dat2.900[-inTraining, ]

# run GAM
gam900 <- gam(formula = log_den_NERLUE ~ 
              s(log_den_STRPURAD, k = 5, bs = "cr") + # purple sea urchins
              s(Max_Monthly_Nitrate, k = 5, bs = "cr") + 
              s(wh_max, k = 5, bs = "cr") + # wave height
              s(log_UBR_Max, k = 4, bs = "cr") + # orbital velocity, continuous variables
              s(site_name, zone, bs = "re") + # zone is nested within site
              s(year, bs = "re"), # discrete variables, categorical
              # random factor
              family = tw(), data = train.900, method = 'REML')

# check GAM
gam900$aic
gam900$deviance
summary(gam900)
gam.check(gam900)
```

```{r}
# plot observed vs predicted

# fit the testing data
fits900 <- predict.gam(gam900, newdata = test.900, type = 'response', se.fit = T)

predicts.all <- test.900 %>%
  data.frame(fits900) %>%
  ungroup()

library(ggpmisc)

my.formula <- y ~ x

p <- predicts.all %>%
  ggplot(aes(x = fit, y = log_den_NERLUE)) + 
  geom_smooth(method = 'lm', se = FALSE, color = 'black', formula = my.formula) + 
  stat_poly_eq(
    formula = my.formula,
    aes(label = paste(..eq.label.., ..rr.label.., sep = '~~~')),
    parse = TRUE
  ) + 
  geom_point() + 
  labs(x = 'Predicted', y = 'Observed', title = 'N. luetkeana') + 
  theme_bw()
p
```

## 1500x1500

```{r}
data.1500 <- data.frame(site_name = factor(),
                       year = factor(),
                       log_den_STRPURAD = numeric())
  
year <- c(2004:2021)
urchin.1500 <- rast(paste(urch.dir, 'Log_Purple_Urchins_1500m.tif', sep = '/')) 

for (i in 1:length(year)) {
  urch.rast <- urchin.1500[[i]]
  urch.ext <- terra::extract(urch.rast, vect(site.shp$geometry)) %>%
    mutate(site_name = as.factor(site$site_name), year = as.factor(year[i]), .before = fit) %>%
    dplyr::select(-ID) 
  data.1500 <- rbind(data.1500, setNames(urch.ext, names(data.1500)))
}

max_nit.1500 <- rast(paste(nit.dir, 'Max_Monthly_Nitrate_1500m.tif', sep = '/')) 
max_nit.1500 <- max_nit.1500[[-c(1:6)]] # remove years before 2004
whmax.1500 <- rast(paste(wave.dir, 'wh_max_1500m.tif', sep = '/')) 
# ubr.1500 <- rast(paste(ubr.dir, 'UBR_Max_1500m.tif', sep = '/'))
# ubr.1500 <- terra::project(ubr.1500, 'epsg:4326')
# writeRaster(ubr.1500, file.path(ubr.dir, 'UBR_Max_1500m_projected.tif'), overwrite = TRUE)
ubr.1500 <- rast(paste(ubr.dir, 'UBR_Max_1500m_projected.tif', sep = '/')) 

nit.df <- data.frame(Max_Monthly_Nitrate = numeric())
whmax.df <- data.frame(wh_max = numeric())
ubr.df <- data.frame(UBR_Max = numeric())
for (i in 1:length(year)) {
  nit.rast <- max_nit.1500[[i]]
  nit.ext <- terra::extract(nit.rast, vect(site.shp$geometry)) %>%
    dplyr::select(-ID) 
  nit.df <- rbind(nit.df, setNames(nit.ext, names(nit.df)))
  
  whmax.rast <- whmax.1500[[i]]
  whmax.ext <- terra::extract(whmax.rast, vect(site.shp$geometry)) %>%
    dplyr::select(-ID) 
  whmax.df <- rbind(whmax.df, setNames(whmax.ext, names(whmax.df)))
  
  ubr.rast <- ubr.1500[[i]]
  ubr.ext <- terra::extract(ubr.rast, vect(site.shp$geometry)) %>%
    dplyr::select(-ID) 
  ubr.df <- rbind(ubr.df, setNames(ubr.ext, names(ubr.df)))
}
```

```{r}
data.1500 <- cbind(data.1500, nit.df, whmax.df, ubr.df) 
df.1500 <- data.1500 %>%
  mutate(log_UBR_Max = log(UBR_Max)) %>% # log transformation of UBR
  dplyr::select(-UBR_Max)
```

```{r}
dat.1500 <- left_join(dat2, df.1500, by = c('site_name', 'year'))
# write.csv(dat.1500, file.path(d.dir, '/RCCA_kelp_inverts_NC_depth-zones_wave_clim_temp_nit_subs_orbvel_npp_1500m.csv'), row.names = FALSE)

# drop NAs
dat2.1500 <- dat.1500 %>%
  drop_na() # 434

# divide data into train and test
# split data into a training set (75%), and a testing set (25%)
set.seed(110122)
inTraining <- createDataPartition(dat2.1500$log_den_NERLUE, p = 0.75, list = FALSE)
train.1500 <- dat2.1500[inTraining, ]
test.1500 <- dat2.1500[-inTraining, ]

# run GAM
gam1500 <- gam(formula = log_den_NERLUE ~ 
              s(log_den_STRPURAD, k = 5, bs = "cr") + # purple sea urchins
              s(Max_Monthly_Nitrate, k = 5, bs = "cr") + 
              s(wh_max, k = 5, bs = "cr") + # wave height
              s(log_UBR_Max, k = 4, bs = "cr") + # orbital velocity, continuous variables
              s(site_name, zone, bs = "re") + # zone is nested within site
              s(year, bs = "re"), # discrete variables, categorical
              # random factor
              family = tw(), data = train.1500, method = 'REML')

# check GAM
gam1500$aic
gam1500$deviance
summary(gam1500)
gam.check(gam1500)
```

```{r}
# plot observed vs predicted

# fit the testing data
fits1500 <- predict.gam(gam1500, newdata = test.1500, type = 'response', se.fit = T)

predicts.all <- test.1500 %>%
  data.frame(fits1500) %>%
  ungroup()

library(ggpmisc)

my.formula <- y ~ x

p <- predicts.all %>%
  ggplot(aes(x = fit, y = log_den_NERLUE)) + 
  geom_smooth(method = 'lm', se = FALSE, color = 'black', formula = my.formula) + 
  stat_poly_eq(
    formula = my.formula,
    aes(label = paste(..eq.label.., ..rr.label.., sep = '~~~')),
    parse = TRUE
  ) + 
  geom_point() + 
  labs(x = 'Predicted', y = 'Observed', title = 'N. luetkeana') + 
  theme_bw()
p
```

## Summary

```{r}
result <- data.frame(resolution = factor(c(120, 300, 900, 1500)),
                     R2.train = c(0.641, 0.63, 0.539, 0.625),
                     deviance = c(gam120$deviance, gam300$deviance, 
                                  gam900$deviance, gam1500$deviance),
                     AIC = c(gam120$aic, gam300$aic, gam900$aic, gam1500$aic),
                     R2.test = c(0.47, 0.57, 0.51, 0.52))
result
```